// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of beverages_List ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class beverages_ListViewModel : ViewModelsBase.VMBase, IViewModels.Ibeverages_ListViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly Repositories.Ibeverages_beveragesCollection _beverages_beveragesCollection;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="beverages_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="beverages_beveragesCollection">The Beverages_beverages Collection.</param>
        public beverages_ListViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, Repositories.Ibeverages_beveragesCollection beverages_beveragesCollection)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_beverages_beveragesCollection = beverages_beveragesCollection;
        }
		
	
		private ObservableCollection<Entities.beveragesSchema> _beverages_ListListControlCollection;

        /// <summary>
        /// Beverages_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.beveragesSchema> Beverages_ListListControlCollection
        {
            get
            {
				
                if(_beverages_ListListControlCollection == null)
					_beverages_ListListControlCollection = _beverages_beveragesCollection.GetData();
				return _beverages_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _beverages_ListListControlCollection, value);
            }
        }
	
		private int _beverages_ListListControlCollectionPageNumber;

        /// <summary>
        /// Beverages_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int Beverages_ListListControlCollectionPageNumber
        {
            get
            {
				return _beverages_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _beverages_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.beveragesSchema _selectedbeverages_ListListControlCollection;

        /// <summary>
        /// Selectedbeverages_ListListControlCollection property.
        /// </summary>		
        public Entities.beveragesSchema Selectedbeverages_ListListControlCollection
        {
            get
            {
				return _selectedbeverages_ListListControlCollection;
            }
            set
            {
                _selectedbeverages_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Ibeverages_DetailViewModel>(_selectedbeverages_ListListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the Getbeverages_ListListControlCollectionCommand command.
        /// </summary>
        public  void Getbeverages_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getbeverages_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getbeverages_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the Getbeverages_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand Getbeverages_ListListControlCollectionCommand
        {
            get { return _getbeverages_ListListControlCollectionCommand = _getbeverages_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getbeverages_ListListControlCollectionCommandDelegate); }
        }

        private void Getbeverages_ListListControlCollectionData(int pageNumber = 0)
        {
				Beverages_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _beverages_beveragesCollection.GetData(pageNumber);
                    Beverages_ListListControlCollection = items;
				}
                else   
				{
					var items = _beverages_beveragesCollection.GetData(pageNumber);
                    foreach (var item in items)                    
                        Beverages_ListListControlCollection.Add(item);
				}
		}
    }
}
