// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of desserts_List ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class desserts_ListViewModel : ViewModelsBase.VMBase, IViewModels.Idesserts_ListViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly Repositories.Idesserts_dessertsCollection _desserts_dessertsCollection;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="desserts_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="desserts_dessertsCollection">The Desserts_desserts Collection.</param>
        public desserts_ListViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, Repositories.Idesserts_dessertsCollection desserts_dessertsCollection)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_desserts_dessertsCollection = desserts_dessertsCollection;
        }
		
	
		private ObservableCollection<Entities.dessertsSchema> _desserts_ListListControlCollection;

        /// <summary>
        /// Desserts_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.dessertsSchema> Desserts_ListListControlCollection
        {
            get
            {
				
                if(_desserts_ListListControlCollection == null)
					_desserts_ListListControlCollection = _desserts_dessertsCollection.GetData();
				return _desserts_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _desserts_ListListControlCollection, value);
            }
        }
	
		private int _desserts_ListListControlCollectionPageNumber;

        /// <summary>
        /// Desserts_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int Desserts_ListListControlCollectionPageNumber
        {
            get
            {
				return _desserts_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _desserts_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.dessertsSchema _selecteddesserts_ListListControlCollection;

        /// <summary>
        /// Selecteddesserts_ListListControlCollection property.
        /// </summary>		
        public Entities.dessertsSchema Selecteddesserts_ListListControlCollection
        {
            get
            {
				return _selecteddesserts_ListListControlCollection;
            }
            set
            {
                _selecteddesserts_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Idesserts_DetailViewModel>(_selecteddesserts_ListListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the Getdesserts_ListListControlCollectionCommand command.
        /// </summary>
        public  void Getdesserts_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getdesserts_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getdesserts_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the Getdesserts_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand Getdesserts_ListListControlCollectionCommand
        {
            get { return _getdesserts_ListListControlCollectionCommand = _getdesserts_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getdesserts_ListListControlCollectionCommandDelegate); }
        }

        private void Getdesserts_ListListControlCollectionData(int pageNumber = 0)
        {
				Desserts_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _desserts_dessertsCollection.GetData(pageNumber);
                    Desserts_ListListControlCollection = items;
				}
                else   
				{
					var items = _desserts_dessertsCollection.GetData(pageNumber);
                    foreach (var item in items)                    
                        Desserts_ListListControlCollection.Add(item);
				}
		}
    }
}
