// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of starters_List ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class starters_ListViewModel : ViewModelsBase.VMBase, IViewModels.Istarters_ListViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly Repositories.Istarters_startersCollection _starters_startersCollection;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="starters_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="starters_startersCollection">The Starters_starters Collection.</param>
        public starters_ListViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, Repositories.Istarters_startersCollection starters_startersCollection)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_starters_startersCollection = starters_startersCollection;
        }
		
	
		private ObservableCollection<Entities.startersSchema> _starters_ListListControlCollection;

        /// <summary>
        /// Starters_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.startersSchema> Starters_ListListControlCollection
        {
            get
            {
				
                if(_starters_ListListControlCollection == null)
					_starters_ListListControlCollection = _starters_startersCollection.GetData();
				return _starters_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _starters_ListListControlCollection, value);
            }
        }
	
		private int _starters_ListListControlCollectionPageNumber;

        /// <summary>
        /// Starters_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int Starters_ListListControlCollectionPageNumber
        {
            get
            {
				return _starters_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _starters_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.startersSchema _selectedstarters_ListListControlCollection;

        /// <summary>
        /// Selectedstarters_ListListControlCollection property.
        /// </summary>		
        public Entities.startersSchema Selectedstarters_ListListControlCollection
        {
            get
            {
				return _selectedstarters_ListListControlCollection;
            }
            set
            {
                _selectedstarters_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Istarters_DetailViewModel>(_selectedstarters_ListListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the Getstarters_ListListControlCollectionCommand command.
        /// </summary>
        public  void Getstarters_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getstarters_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getstarters_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the Getstarters_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand Getstarters_ListListControlCollectionCommand
        {
            get { return _getstarters_ListListControlCollectionCommand = _getstarters_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getstarters_ListListControlCollectionCommandDelegate); }
        }

        private void Getstarters_ListListControlCollectionData(int pageNumber = 0)
        {
				Starters_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _starters_startersCollection.GetData(pageNumber);
                    Starters_ListListControlCollection = items;
				}
                else   
				{
					var items = _starters_startersCollection.GetData(pageNumber);
                    foreach (var item in items)                    
                        Starters_ListListControlCollection.Add(item);
				}
		}
    }
}
