// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// beverages_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Ibeverages_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentbeveragesSchema property.
        /// </summary>
		Entities.beveragesSchema CurrentbeveragesSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramabeverages_Detail0 property.
        /// </summary>
		bool HasNextpanoramabeverages_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramabeverages_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramabeverages_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechbeverages_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechbeverages_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharebeverages_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharebeverages_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartbeverages_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartbeverages_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramabeverages_Detail0 command.
        /// </summary>
		ICommand Nextpanoramabeverages_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramabeverages_Detail0 command.
        /// </summary>
		ICommand Previouspanoramabeverages_Detail0 { get; }

	}
}
