// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// beverages_List ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Ibeverages_ListViewModel
    {		
        /// <summary>
        /// Gets/Sets the Beverages_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.beveragesSchema> Beverages_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Beverages_ListListControlCollectionPageNumber property.
        /// </summary>
		int Beverages_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the Selectedbeverages_ListListControlCollection property.
        /// </summary>
		Entities.beveragesSchema Selectedbeverages_ListListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the Getbeverages_ListListControlCollectionCommand command.
        /// </summary>
		ICommand Getbeverages_ListListControlCollectionCommand { get; }

	}
}
