// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// desserts_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Idesserts_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentdessertsSchema property.
        /// </summary>
		Entities.dessertsSchema CurrentdessertsSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramadesserts_Detail0 property.
        /// </summary>
		bool HasNextpanoramadesserts_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramadesserts_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramadesserts_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechdesserts_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechdesserts_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharedesserts_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharedesserts_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartdesserts_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartdesserts_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramadesserts_Detail0 command.
        /// </summary>
		ICommand Nextpanoramadesserts_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramadesserts_Detail0 command.
        /// </summary>
		ICommand Previouspanoramadesserts_Detail0 { get; }

	}
}
