// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// starters_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Istarters_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentstartersSchema property.
        /// </summary>
		Entities.startersSchema CurrentstartersSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramastarters_Detail0 property.
        /// </summary>
		bool HasNextpanoramastarters_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramastarters_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramastarters_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechstarters_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechstarters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharestarters_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharestarters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartstarters_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartstarters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramastarters_Detail0 command.
        /// </summary>
		ICommand Nextpanoramastarters_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramastarters_Detail0 command.
        /// </summary>
		ICommand Previouspanoramastarters_Detail0 { get; }

	}
}
