// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// starters_startersCollection interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Istarters_startersCollection
    {
		ObservableCollection<Entities.startersSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.startersSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.startersSchema current);
		bool HasNext(Entities.startersSchema current);
		Entities.startersSchema Previous(Entities.startersSchema current);
		Entities.startersSchema Next(Entities.startersSchema current);
    }
}
