// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// desserts_dessertsCollection data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class desserts_dessertsCollection : Idesserts_dessertsCollection 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.dessertsSchema> _data = new ObservableCollection<Entities.dessertsSchema>
		{
          new Entities.dessertsSchema
            {
                Id= new Guid("d4230b70-85e4-4dc3-8227-092bdef3767d"),
                Title=@"Brunei ",
                Subtitle=@"กล้วยแขก Fried banana ",
                Image=@"\Images\Item-4ec2f660-1881-4b44-9c38-896561b26857.jpg",
                Description=@"กล้วยทอด หรือกล้วยแขก ประวัติและที่มาของกล้วยแขกทอด ไม่ทราบแน่ชัด แต่กล้วยแขกน่าจะเป็นอาหารที่มาจากวัฒนธรรมการปรุงอาหารของชาวอินเดีย ซึ่งจะใช้การทอด เหมือนกับถั่วทอด ซึ่งแตกต่างกับวัฒนธรรมการปรุงอาหารของไทย ซึ่งใช้ต้ม ปิ้ง ย่าง เป็นหลัก เช่น กล้วยบวชชี กล้วยต้มมะพร้าวขูดโรยน้ำตาล กล้วยปิ้ง ขนมกล้วยที่ต้องห่อใบตองย่าง บ้างก็ว่าเป็นขนมที่ชาวโปตุเกตุนำเข้ามาประเทศไทย เลยยังเป็นข้อถกเถียงกันเรื่อยมา ยังหาข้อพิสูจน์ไม่ได้",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("d6f9f8db-3426-42fa-aace-ba8534ace78b"),
                Title=@"Cambodia ",
                Subtitle=@"กระยาสารท Krayasart",
                Image=@"\Images\Item-f092fb1e-f635-4a3e-b289-63c8d6822ceb.jpg",
                Description=@"กระยาสารท แปลว่าอาหารที่ทำให้ฤดูสารท กระยาสารทนี้เนื่องมาจาก ข้าวมธุปายาส ซึ่งเป็นอาหารอินเดียใช้ข้าว น ้าตาล น ้านม ผสมกัน ซึ่งนางสุชาดาหุงถวายพระพุทธเจ้าส่วนผสมของกระยาสารทไทยมีข้าวตอก ข้าวเม่า ถั่วลิสง งาคั่วให้สุกเสียก่อน แล้วนำมากวนกับน ้าอ้อยกวนให้เหนียวกรอบเกาะกันเป็นปึก จะทำเป็นกรอบเป็นก้อนหรือตัดเป็นชิ้นๆ เก็บไว้ได้นานทำจากพืชผลแรกได้กระยาสารทเป็นของหวานจัด โดยมากจะกินกับกล้วยไข่สุกทำถวายพระเพื่ออุทิศส่วนกุศลให้ผู้ที่ล่วงลับไปแล้ว กระยาสารทกำหนดทรงบาตรที่วิเศษ ในการพระราชพิธีสารทนี้ตกทอดกันมานาน",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("bcb8ae0c-d51a-463d-8b43-893f2fec049c"),
                Title=@"Indonesia ",
                Subtitle=@"วุ้นมะพร้าว jelly Coconut",
                Image=@"\Images\Item-4f143c39-b740-4eb9-b2e0-ebe32da49370.jpg",
                Description=@"วุ้นมะพร้าว หรือ วุ้นสวรรค์ หรือเป็นที่รู้จักกันในชื่อ“NATA de coco” เป็นผลิตภัณฑ์ที่ได้จากการกระบวนการหมักน้ำมะพร้าว ซึ่งเป็นของเหลือทิ้งทางการเกษตร โดยกิจกรรมของแบคทีเรียกรดน้ำส้ม (Acetic acid bacteria) ที่พบได้ทั่วไปในการทำน้ำส้มสายชูหมักตามธรรมชาติ  แบคทีเรียกรดน้ำส้มนี้มีชื่อเรียกว่า Acetobacter xylinum  ผลผลิตจากกระบวนการหมักของแบคทีเรียกรดน้ำส้มนี้คือ โพลิแซคคาร์ไรด์ หรือที่เรียกกันติดปากว่า “วุ้นน้ำมะพร้าว (วุ้นสวรรค์)”นั้นเอง ",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("51e46b22-fe94-423b-af56-7f9c70cb1286"),
                Title=@"Laos ",
                Subtitle=@"น้ำตาลอ้อย sugar cane",
                Image=@"\Images\Item-ff75ae60-7a65-4c75-aa69-e6b0e15da77f.jpg",
                Description=@"                    น้ำตาลอ้อยผูกพันกับวิถีชีวิตคนไทยมาช้านาน โดยเฉพาะขนมท้องถิ่นต่างๆล้วนใช้น้ำตาลจากอ้อย เช่น ขนมกระยาสารทที่ต้องใช้น้ำอ้อยกวนจึงจะหอมอร่อย ขนมวงทราราดนห้าด้วยน้ำตาลอ้อยเคี่ยวจนเหนียว เช่นเดียวกับขนมนางเล็ดหรือข้าวแต๋น และขนมเทียน ขนมเข่ง ขนมต้ม ข้าวเหนียวแดง ฯลฯ ก็ใช้น้ำตาลอ้อยเพิ่มรสชาติและความหอม",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("65962fdc-c261-411d-a5dd-a63171846808"),
                Title=@"Malaysia ",
                Subtitle=@"โรตี southern flat bread",
                Image=@"\Images\Item-f35f5cb7-4b24-4be6-b03f-c0f6e5e86643.jpg",
                Description=@"             โรตี เป็นอาหารชนิดหนึ่ง ทำจากแป้ง นวดแล้วนำไปทอดหรือปิ้งเป็นแผ่นบางๆ รับประทานเป็นของหวาน หรือรับประทานพร้อมอาหารคาวอื่นๆ ก็ได้ ในประเทศไทยมักจะคุ้นกับโรตีที่ทอดเป็นแผ่นนุ่ม ราดด้วยนมข้นและน้ำตาลทราย เป็นของหวาน
            คำว่า โรตี เป็นคำศัพท์ที่พบได้ในหลายภาษา ได้แก่ ภาษาฮินดี, อุรดู, ปัญจาบี, โซมาลี, อินโดนีเซีย และ มลายู ซึ่งล้วนแต่มีความหมายว่า ขนมปัง
",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("1d3ac474-a6ae-4a09-a131-a476ad8d4a19"),
                Title=@"Myanmar ",
                Subtitle=@" ข้าวต้มมัด",
                Image=@"\Images\Item-5a0d5c2f-aaaa-4fcd-b309-c658846efb6f.jpg",
                Description=@"ข้าวต้มมัด หรือ ข้าวต้มผัด เป็นขนมชนิดหนึ่งที่ทำด้วยข้าวเหนียวผัดกับกะทิ แล้วนำไปห่อด้วยใบตองหรือใบมะพร้าวอ่อน ใส่ไส้กล้วย นำไปนึ่งให้สุก ทางภาคใต้ใช้ข้าวเหนียวกับน้ำกะทิ ห่อด้วยใบพ้อ เรียกห่อต้ม ถ้าห่อด้วยใบมะพร้าว และมัดด้วยเชือกเรียกห่อมัด ขนมแบบเดียวกับข้าวต้มยังพบในประเทศอื่นอีก เช่นในฟิลิปปินส์เรียก อีบอส หรือ ซูมัน ที่แบ่งย่อยได้หลายชนิดเช่นเดียวกับข้าวต้มมัดของไทย ",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("851dd565-f5c6-48b8-b548-a966ec8ce198"),
                Title=@"Philippines ",
                Subtitle=@"ฮาโลฮาโล, Halo-Halo",
                Image=@"\Images\Item-b98113bc-97e1-4ada-9c6a-6577b794ddc5.jpg",
                Description=@"                        จานเด็ดของชาวฟิลิปปินส์ที่มีชื่อเสียงโด่งดังไม่แพ้ไข่บาลุท แต่รับประกันได้ว่าไม่น่าสะอิดสะเอียน ทั้งนี้ ฮาโล ฮาโล ไม่มีสูตรการทำที่แน่นอน แต่ดูๆไปก็ไม่ต่างอะไรกับน้ำแข็งใสของบ้านเรา โดยนำน้ำแข็งบดมาเติมด้วยเครื่องเคียง เช่น ถั่วเขียว ลูกตาล ขนุน มะพร้าวอ่อน ไอศกรีม วุ้นมะพร้าว สับปะรด และอื่นๆ ก่อนจะปิดท้ายด้วยการราดนมข้นหวานและน้ำเชื่อม โดยสามารถหารับประทานได้ทุกที่ในกรุงมะนิลา",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("8b95d88a-09f9-4465-b861-9579835c654d"),
                Title=@"Singapore ",
                Subtitle=@"ลอดช่องสิงคโปร์ Ladcheag Singapore",
                Image=@"\Images\Item-8bd783a8-930c-4d7d-9250-742bcc3437a7.jpg",
                Description=@"                      ลอดช่อง.. .เป็นขนมไทยแท้โบราณชนิดดั้งเดิม โดยที่ใครๆพากันคิดว่ามันคือขนม ที่มาจากเกาะสิงคโปร์นู้นแต่แท้จริงแล้วต้นกำเนิดไม่ได้มาจากประเทศสิงคโปร์ แต่เกิดจากภูมิปัญญาของคนไทยเรานี่เอง ที่ได้นำแป้งมันสำปะหลังมาปั้น และนวดให้เหนียว รับประทานกับกะทิสด และน้ำเชื่อม น้ำแข็งป่น ก็เพิ่มความสดชื่นให้กับผู้บริโภคได้แล้ว แต่หลายคนคงสงสัยว่าแล้วคำว่า สิงคโปร์ล่ะ มาจากไหน ซึ่งเป็นชื่อที่เรียกกันจนติดปาก ถึงบริเวณที่ตั้งร้านนี้ ที่เป็นเจ้าแรก ในการทำ “ลอดช่องสิงคโปร์”นั่นเอง",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("6a8e9596-9b6f-41f9-ac25-467a59a3afae"),
                Title=@"Thailand ",
                Subtitle=@"บัวลอย Bualoy",
                Image=@"\Images\Item-faadf7e7-1db0-487d-9b48-f18f0587a20c.jpg",
                Description=@" ตำนานบัวลอย จะว่ามีที่มาจากขนมบัวลอยก็ไม่เชิง แต่จะว่าไม่ใช่ก็ไม่ได้เหตุเกิด จากเมื่ออดีตกาลนานมาแล้วมีสตรีตั้งท้องต้องการที่จะช่วยแบ่งเบาภาระผัวโดยการทำขนมขาย แม้ผัวจะห้ามปราอย่างไรก็ไม่ฟัง เมื่อผัวไปทำงานก็จะทำขนมบัวลอยใส่เรือแล้วพาย ไปขายในคลอง ชาวบ้านที่จะซื้อก็จะตะโกน
 “บัวลอยจ้า..บัวลอยมาทางนี้หน่อย"" และด้วยขนมบัวลอยทำจากกระทิ เมื่อทำเสร็จแล้วก็เอาลงเรือขายเลยประกอบกับฝีมือการทำขนม บัวลอยที่มีความอร่อยจนติดอกติดใจชาวบ้าน จนใครๆก็เรียกเธอว่า “บัวลอย”
",
			},
          new Entities.dessertsSchema
            {
                Id= new Guid("eff9bb56-ceee-4970-bccd-5388804b3fe6"),
                Title=@"Vietnam",
                Subtitle=@" ขนมเบื้องญวน",
                Image=@"\Images\Item-a419ec11-f1e3-47dc-b453-deb033df1490.jpg",
                Description=@" ขนมเบื้องเป็นขนมไทยที่มีมาตั้งแต่สมัยโบราณ มีหลักฐานกล่าวถึงในคำให้การขุนหลวงหาวัดว่า ""บ้านหม้อปั้นหม้อข้าวหม้อแกงใหญ่เล็ก และกระทะเตาขนมครกขนมเบื้อง"" ขนมเบื้องมี 2 แบบคือขนมเบื้องไทย โดยทั่วไปมี 2หน้าคือหน้ากุ้งและหน้าหวาน หน้ากุ้งใช้กุ้งแม่น้ำตัวโตสับละเอียดผสมกับพริกไทยและผักชีตำพร้อมมันกุ้ง นำไปผัดใส่น้ำตาล น้ำปลาหรือเกลือให้หอม ปัจจุบันมักเป็นหน้ามะพร้าวใส่สีแดง ส่วนหน้าหวานมีส่วนผสมของฟักเชื่อม ฝอยทองและพลับแห้งที่หั่นบางๆ ปัจจุบันมีแต่ฝอยทองกับครีม อย่างไรก็ตามในวังสวนสุนันทา มีหน้าหมูอีกอย่างหนึ่ง ใช้หมูสับคลุกคล้ากับกระเทียม พริกไทย รากผักชีโขลก ใส่พริกขี้หนู นำไปรวนพอสุก ขนมเบื้องญวน เป็นขนมที่เข้ามาพร้อมกับเชลยชาวญวนในสมัยรัชกาลที่ 3 ซึ่งถูกกวาดต้อนมาระหว่างสงครามสยาม-เวียดนาม ขนมนี้ทำจากแป้งละลายกับไข่ให้ข้น ตักแป้งเทลงในกระทะที่ทาน้ำมันไว้ แผ่เป็นแผ่นกลม ใส่ไส้แล้วพับกลาง",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of dessertsSchema items.
        /// </summary>
        /// <returns>An observable collection of dessertsSchema items.</returns>
        public ObservableCollection<Entities.dessertsSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.dessertsSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of dessertsSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of dessertsSchema items.</returns>
        public ObservableCollection<Entities.dessertsSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.dessertsSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.dessertsSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.dessertsSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.dessertsSchema Previous(Entities.dessertsSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.dessertsSchema Next(Entities.dessertsSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

