// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using Ioc=WPAppStudio.Ioc;
using IViewModels=WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IIoc.IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Ioc.Container();
        }
		
		/// <summary>
        /// Resolve a service of type T
        /// </summary>
        /// <typeparam name="T">Type of the service.</typeparam>
        /// <returns></returns>
        public T ResolveService<T>()
        {
            return _container.Resolve<T>();
        }

        /// <summary>
        /// Gets the reference to a navigate_MenuViewModel.
        /// </summary>
		public IViewModels.Inavigate_MenuViewModel navigate_MenuViewModel
        {
            get { return _container.Resolve<IViewModels.Inavigate_MenuViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a starters_ListViewModel.
        /// </summary>
		public IViewModels.Istarters_ListViewModel starters_ListViewModel
        {
            get { return _container.Resolve<IViewModels.Istarters_ListViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a starters_DetailViewModel.
        /// </summary>
		public IViewModels.Istarters_DetailViewModel starters_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.Istarters_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a desserts_ListViewModel.
        /// </summary>
		public IViewModels.Idesserts_ListViewModel desserts_ListViewModel
        {
            get { return _container.Resolve<IViewModels.Idesserts_ListViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a desserts_DetailViewModel.
        /// </summary>
		public IViewModels.Idesserts_DetailViewModel desserts_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.Idesserts_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a beverages_ListViewModel.
        /// </summary>
		public IViewModels.Ibeverages_ListViewModel beverages_ListViewModel
        {
            get { return _container.Resolve<IViewModels.Ibeverages_ListViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a beverages_DetailViewModel.
        /// </summary>
		public IViewModels.Ibeverages_DetailViewModel beverages_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.Ibeverages_DetailViewModel>(); }
        }
		/// <summary>
        /// Gets the reference to a AboutViewModel.
        /// </summary>
		public IViewModels.IAboutViewModel AboutViewModel
        {
            get { return _container.Resolve<IViewModels.IAboutViewModel>(); }
        }
		
		/// <summary>
        /// Gets the reference to a LicenseViewModel.
        /// </summary>
		public IViewModels.ILicenseViewModel LicenseViewModel
        {
            get { return _container.Resolve<IViewModels.ILicenseViewModel>(); }
        }
    }
}
